name: Lint
on:
  push:
    branches-ignore:
      - gh-pages
      - releases/**
  pull_request:
    branches-ignore:
      - gh-pages
      - releases/**
    types:
      - opened
      - synchronize
      - reopened
permissions:
  contents: read
env:
  CI: true

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 6.10.0
      - name: Setup Node.js v14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm run lint
